# Generated by Django 5.0.7 on 2024-08-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectureproject',
            name='architecture_project_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
