# Generated by Django 5.0.7 on 2024-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_projects', '0002_alter_architectureproject_architecture_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architectureproject',
            old_name='description',
            new_name='architecture_project_description',
        ),
        migrations.AlterField(
            model_name='architectureproject',
            name='architecture_project_name',
            field=models.CharField(max_length=100, verbose_name='Nombre Proyecto Arquitectura'),
        ),
    ]
