# Generated by Django 5.0.7 on 2024-08-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_projects', '0003_rename_description_architectureproject_architecture_project_description_and_more'),
        ('projects', '0010_remove_project_unique_project_name_per_owner_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='architectureproject',
            constraint=models.UniqueConstraint(fields=('architecture_project_name', 'project'), name='unique_architecture_project_name_per_project'),
        ),
    ]
