# Generated by Django 5.0.7 on 2024-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_projects', '0004_architectureproject_unique_architecture_project_name_per_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='obranueva',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del proyecto'),
        ),
    ]
