# Generated by Django 5.0.7 on 2024-08-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_projects', '0005_obranueva_nombre_proyecto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='architectureproject',
            name='unique_architecture_project_name_per_project',
        ),
    ]
