# Generated by Django 5.0.7 on 2024-08-18 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_projects', '0006_remove_architectureproject_unique_architecture_project_name_per_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_group', models.CharField(max_length=255, verbose_name='Grupo de Permisos')),
            ],
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(max_length=255, verbose_name='Tipo de Permiso')),
            ],
        ),
        migrations.AlterField(
            model_name='architectureproject',
            name='architecture_project_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Proyecto Arquitectura'),
        ),
        migrations.CreateModel(
            name='PermitSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_sub_type', models.CharField(max_length=255, verbose_name='Subtipo de Permiso')),
                ('permit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpermit_types', to='architecture_projects.permitgroup', verbose_name='Grupo de Permisos')),
            ],
        ),
        migrations.AddField(
            model_name='permitgroup',
            name='permit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpermit_types', to='architecture_projects.permittype', verbose_name='Tipo de Permiso'),
        ),
    ]
