# Generated by Django 5.0.7 on 2024-08-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_projects', '0008_carga_inicial_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitgroup',
            name='permit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_groups', to='architecture_projects.permittype', verbose_name='Tipo de Permiso'),
        ),
        migrations.AlterField(
            model_name='permitsubtype',
            name='permit_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_subtypes', to='architecture_projects.permitgroup', verbose_name='Grupo de Permisos'),
        ),
    ]
