# Generated by Django 4.2.2 on 2024-07-06 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regioncomuna', '0002_crear_regiones_y_comunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_date', models.DateField(verbose_name='Fecha de Permiso')),
                ('permit_number', models.CharField(max_length=100, verbose_name='Número de Permiso')),
                ('file', models.FileField(blank=True, null=True, upload_to='permits/', verbose_name='Archivo de Permiso')),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Permiso')),
                ('type', models.CharField(choices=[('Obra Menor', 'Obra Menor'), ('Anteproyecto', 'Anteproyecto'), ('Obra Nueva', 'Obra Nueva')], default='Construcción', max_length=20, verbose_name='Tipo de Permiso')),
                ('permit_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario de Permiso')),
            ],
            options={
                'verbose_name': 'Permiso de la Propiedad',
                'verbose_name_plural': 'Permisos de la Propiedad',
                'ordering': ['permit_date'],
            },
        ),
        migrations.CreateModel(
            name='CountyRecorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Conservador')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.comuna', verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Propiedad')),
                ('rol', models.CharField(max_length=100, verbose_name='Rol de la Propiedad')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('block', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuadra')),
                ('allotment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Población, Loteo, Villa')),
                ('subdivision_plan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plano de loteo N°')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regioncomuna.comuna', verbose_name='Comuna')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regioncomuna.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='WaterCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Número de Certificado')),
                ('certificate_date', models.DateField(verbose_name='Fecha de Certificado')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Archivo de Certificado')),
                ('certificate_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario de Certificado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_certificate', to='propertys.property')),
            ],
            options={
                'verbose_name': 'Certificado de Agua',
                'verbose_name_plural': 'Certificados de Agua',
                'ordering': ['certificate_date'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Hipotecas y Gravámenes', 'Hipotecas y Gravámenes'), ('Propiedad', 'Propiedad'), ('Prohibiciones', 'Prohibiciones')], default='Propiedad', max_length=30, verbose_name='Tipo de Certificado')),
                ('leaves', models.CharField(max_length=100, verbose_name='Fojas')),
                ('number', models.CharField(max_length=100, verbose_name='Número')),
                ('year', models.CharField(max_length=100, verbose_name='Año')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Archivo de Certificado')),
                ('certificate_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario de Certificado')),
                ('county_recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertys.countyrecorder', verbose_name='county_recorder')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_certificate', to='propertys.property')),
            ],
            options={
                'verbose_name': 'Certificado de Patente',
                'verbose_name_plural': 'Certificados de Patente',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='GasCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Número de Certificado')),
                ('certificate_date', models.DateField(verbose_name='Fecha de Certificado')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Archivo de Certificado')),
                ('certificate_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario de Certificado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_certificate', to='propertys.property')),
            ],
            options={
                'verbose_name': 'Certificado de Gas',
                'verbose_name_plural': 'Certificados de Gas',
                'ordering': ['certificate_date'],
            },
        ),
        migrations.CreateModel(
            name='ElectricCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Número de Certificado')),
                ('certificate_date', models.DateField(verbose_name='Fecha de Certificado')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Archivo de Certificado')),
                ('certificate_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario de Certificado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electric_certificate', to='propertys.property')),
            ],
            options={
                'verbose_name': 'Certificado Eléctrico',
                'verbose_name_plural': 'Certificados Eléctricos',
                'ordering': ['certificate_date'],
            },
        ),
        migrations.CreateModel(
            name='BuildingReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_number', models.CharField(max_length=100, verbose_name='Número de Recepción')),
                ('reception_date', models.DateField(verbose_name='Fecha de Recepción')),
                ('partial_reception', models.BooleanField(default=False, verbose_name='Recepción Parcial')),
                ('file', models.FileField(blank=True, null=True, upload_to='receptions/', verbose_name='Archivo de Recepción')),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Terreno')),
                ('reception_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario de Recepción')),
                ('building_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='propertys.buildingpermit', verbose_name='Permiso de Construcción')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulding_reception', to='propertys.property')),
            ],
            options={
                'verbose_name': 'Recepción de la Propiedad',
                'verbose_name_plural': 'Recepciones de la Propiedad',
                'ordering': ['reception_date'],
            },
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_permit', to='propertys.property'),
        ),
        migrations.CreateModel(
            name='OtherCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100, verbose_name='Nombre del Certificado')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Número de Certificado')),
                ('certificate_date', models.DateField(verbose_name='Fecha de Certificado')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Archivo de Certificado')),
                ('certificate_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario de Certificado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_certificate', to='propertys.property')),
            ],
            options={
                'verbose_name': 'Otros Certificados',
                'verbose_name_plural': 'Otros Certificados',
                'ordering': ['certificate_date'],
                'unique_together': {('property', 'certificate_name')},
            },
        ),
    ]
