# Generated by Django 4.2.2 on 2024-06-25 04:09

import applications.users.functions
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regioncomuna', '0002_crear_regiones_y_comunas'),
        ('users', '0002_rename_encrypted_nombre_completo_user_nombre_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Propietario/a', 'Propietario/a'), ('Arquitecto', 'Arquitecto'), ('Constructor', 'Constructor'), ('Revisor independiente', 'Revisor independiente'), ('Calculista', 'Calculista'), ('Revisor de Cálculo', 'Revisor de Cálculo'), ('Coordinador', 'Coordinador')], max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre_completo',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.comuna'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[applications.users.functions.validar_rut]),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Universidad')),
                ('type', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=7, verbose_name='Tipo')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.region', verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='El puntaje debe ser entre 1 mínimo y 5 como máximo.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=255)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_owner', to=settings.AUTH_USER_MODEL)),
                ('user_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.university')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='patents/')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.comuna')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profession')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.comuna')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_owner', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ManyToManyField(blank=True, related_name='company_partner', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.region')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.ManyToManyField(blank=True, to='users.profession', verbose_name='Profesiones'),
        ),
    ]
