# Generated by Django 4.2.2 on 2024-06-25 04:10

from django.db import migrations


def add_universities(apps, schema_editor):
    University = apps.get_model('users', 'University')
    Region = apps.get_model('regioncomuna', 'Region')
    university_data = [
        {'name': 'Universidad de Chile', 'region': 'Metropolitana de Santiago', 'type': 'publica'},
        {'name': 'Pontificia Universidad Católica de Chile', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad de Concepción', 'region': 'Biobío', 'type': 'publica'},
        {'name': 'Universidad Técnica Federico Santa María', 'region': 'Valparaíso', 'type': 'publica'},
        {'name': 'Universidad de Santiago de Chile', 'region': 'Metropolitana de Santiago', 'type': 'publica'},
        {'name': 'Universidad Austral de Chile', 'region': 'Los Ríos', 'type': 'publica'},
        {'name': 'Pontificia Universidad Católica de Valparaíso', 'region': 'Valparaíso', 'type': 'privada'},
        {'name': 'Universidad Adolfo Ibáñez', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad Diego Portales', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad de Valparaíso', 'region': 'Valparaíso', 'type': 'publica'},
        {'name': 'Universidad de La Frontera', 'region': 'Araucanía', 'type': 'publica'},
        {'name': 'Universidad de los Andes', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad del Desarrollo', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad de Talca', 'region': 'Maule', 'type': 'publica'},
        {'name': 'Universidad Católica del Norte', 'region': 'Antofagasta', 'type': 'privada'},
        {'name': 'Universidad Andrés Bello', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad de los Lagos', 'region': 'Los Lagos', 'type': 'publica'},
        {'name': 'Universidad Central de Chile', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad Tecnológica Metropolitana', 'region': 'Metropolitana de Santiago', 'type': 'publica'},
        {'name': 'Universidad Metropolitana de Ciencias de la Educación', 'region': 'Metropolitana de Santiago',
         'type': 'publica'},
        {'name': 'Universidad de Tarapacá', 'region': 'Arica y Parinacota', 'type': 'publica'},
        {'name': 'Universidad Arturo Prat', 'region': 'Tarapacá', 'type': 'publica'},
        {'name': 'Universidad Católica del Maule', 'region': 'Maule', 'type': 'privada'},
        {'name': 'Universidad Católica de la Santísima Concepción', 'region': 'Biobío', 'type': 'privada'},
        {'name': 'Universidad Católica de Temuco', 'region': 'Araucanía', 'type': 'privada'},
        {'name': 'Universidad Mayor', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad Alberto Hurtado', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad Finis Terrae', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad Gabriela Mistral', 'region': 'Metropolitana de Santiago', 'type': 'privada'},
        {'name': 'Universidad de Magallanes', 'region': 'Magallanes y de la Antártica Chilena', 'type': 'publica'}
    ]

    for uni in university_data:
        region = Region.objects.get(region=uni['region'])
        University.objects.create(name=uni['name'], region=region, type=uni['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_rename_nombre_completo_user_name_user_address_and_more'),
    ]

    operations = [
        migrations.RunPython(add_universities),
    ]
