# Generated by Django 4.2.2 on 2024-07-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('projects', '0003_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='properties.property', verbose_name='Propiedad'),
        ),
    ]
