# Generated by Django 4.2.2 on 2024-07-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='project_owner',
        ),
    ]
