# Generated by Django 5.0.7 on 2024-08-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre del proyecto'),
        ),
    ]
