# Generated by Django 5.0.7 on 2024-08-16 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_name'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(error_messages={'unique': 'Este nombre de proyecto ya existe. Debes escoger otro.'}, max_length=100, verbose_name='Nombre del proyecto'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'project_owner'), name='unique_project_name_per_owner'),
        ),
    ]
