# Generated by Django 4.2.2 on 2024-07-06 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='Currency')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('budget_land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Budget land area')),
                ('land_area_unit', models.CharField(default='m²', max_length=10, verbose_name='Land Area Unit')),
                ('price_per_square_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Price per square unit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_projects', to='projects.project')),
            ],
            options={
                'verbose_name': 'Budget Project',
                'verbose_name_plural': 'Budget Projects',
            },
        ),
        migrations.CreateModel(
            name='BudgetSubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='Currency')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('budget_land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Budget land area')),
                ('land_area_unit', models.CharField(default='m²', max_length=10, verbose_name='Land Area Unit')),
                ('price_per_square_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Price per square unit')),
                ('budget_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_sub_projects', to='budgets.budgetproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('payment_trigger', models.CharField(choices=[('date', 'By Date'), ('milestone', 'By Milestone')], default='date', max_length=10, verbose_name='Payment Trigger')),
                ('is_payment_required', models.BooleanField(default=False, verbose_name='Is payment required')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Payment amount')),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=10, verbose_name='Payment Type')),
                ('time_frame', models.IntegerField(default=0, help_text='Number of days after the start date if by date', verbose_name='Time Frame (days)')),
                ('payment_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of the total project budget if by percentage', max_digits=5, null=True, verbose_name='Payment Percentage')),
                ('milestone', models.CharField(blank=True, help_text='Milestone that triggers the payment', max_length=255, null=True, verbose_name='Milestone')),
                ('budget_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='budgets.budgetproject')),
                ('budget_sub_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='budgets.budgetsubproject')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
    ]
