# Generated by Django 5.0.2 on 2024-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_section_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsection',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
