# Generated by Django 5.0.2 on 2024-03-02 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_element_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='element',
            name='video',
        ),
        migrations.RemoveField(
            model_name='element',
            name='files',
        ),
        migrations.RemoveField(
            model_name='element',
            name='images',
        ),
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='posts.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='articles', to='posts.file'),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='articles', to='posts.image'),
        ),
        migrations.AddField(
            model_name='article',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='articles', to='posts.video'),
        ),
        migrations.AddField(
            model_name='element',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='elements', to='posts.video'),
        ),
        migrations.AddField(
            model_name='element',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='elements', to='posts.file'),
        ),
        migrations.AddField(
            model_name='element',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='elements', to='posts.image'),
        ),
    ]
