# Generated by Django 5.0.2 on 2024-03-03 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_file_image_video_remove_element_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_files', to='posts.article'),
        ),
        migrations.AddField(
            model_name='file',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_files', to='posts.element'),
        ),
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='posts.article'),
        ),
        migrations.AddField(
            model_name='image',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_images', to='posts.element'),
        ),
        migrations.AddField(
            model_name='video',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_videos', to='posts.article'),
        ),
        migrations.AddField(
            model_name='video',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_videos', to='posts.element'),
        ),
    ]
