# Generated by Django 5.0.2 on 2024-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_file_article_file_element_image_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='files',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.RemoveField(
            model_name='article',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='element',
            name='files',
        ),
        migrations.RemoveField(
            model_name='element',
            name='images',
        ),
        migrations.RemoveField(
            model_name='element',
            name='videos',
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Nombre (obligatorio)'),
        ),
    ]
