# Generated by Django 5.0.2 on 2024-03-03 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_article_files_remove_article_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='title',
        ),
        migrations.AddField(
            model_name='element',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='posts.article'),
        ),
    ]
