# Generated by Django 5.0.2 on 2024-03-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_article_description_article_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='reference',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
