# Generated by Django 4.2.2 on 2024-05-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_article_reference_alter_element_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='posts.article'),
        ),
    ]
